name: Prerelease

on:
  pull_request:
    types:
      - labeled
  issue_comment:
    types: [created]

jobs:
  release-alpha:
    name: Alpha Release Gestalt
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      contains(github.event.head_commit.message, 'Version bump:') == false && github.repository == 'pinterest/gestalt' && github.event.label.name == 'prerelease' || 
      contains(github.event.head_commit.message, 'Version bump:') == false && github.repository == 'pinterest/gestalt' && github.event.issue.pull_request && contains(github.event.comment.body, '/alpha')
    steps:
      - name: Set Pre-Release label
        id: extract_labels
        run: |
          echo "::set-output name=labels::["prerelease release"]"
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
      - name: Publish to npm
        run: |
          cd packages/gestalt-design-tokens
          npm dist-tag add gestalt-design-tokens@108.0.0 latest
          cd ../gestalt
          npm dist-tag add gestalt@108.0.0 latest
          cd ../gestalt-datepicker
          npm dist-tag add gestalt-datepicker@108.0.0 latest
          cd ../eslint-plugin-gestalt
          yarn dist-tag add eslint-plugin-gestalt@108.0.0 latest
      - name: Install dependencies
        run: yarn install
      - name: Setup GitHub access tokens
        env:
          RYAN_GITHUB_PERSONAL_TOKEN: ${{ secrets.RYAN_GITHUB_PERSONAL_TOKEN }}
        run: |
          echo "machine github.com" >> ~/.netrc
          echo "login dangerismycat" >> ~/.netrc
          echo "password $RYAN_GITHUB_PERSONAL_TOKEN" >> ~/.netrc
      - name: Release Steps
        id: pre_release
        run: ./scripts/releaseSteps.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: ${{ steps.extract_labels.outputs.labels }}
      - name: Get Github Workflow Version
        run: echo ${{ steps.pre_release.outputs.VERSION }}
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Published alpha-version ${{ steps.pre_release.outputs.VERSION }}! :wave:
