name: 'Label Docs Updates'
on:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'Hello, world!'"
