name: Semver
# https://semver.org/

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
  push:
    branches:
      - master

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.extract_labels.outputs.labels }}
    steps:
      - name: add-label
        id: add-label
        uses: actions/labeler@v5
        with:
          sync-labels: true
          configuration-path: .github/labeler.yml
      - name: Print New Labels
        id: extract_labels
        run: |
          echo "${{ steps.add-label.outputs }}"
          echo "${{ steps.add-label.outputs.new-labels }}"
          echo "::set-output name=labels::${LABELS}"
  requireLabel:
    name: Require Label
    runs-on: ubuntu-latest
    needs: [labeler]
    if: contains(needs.labeler.outputs.labels, 'docs-update') == 'false'
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed: major release, minor release, patch release
