name: Semver
# https://semver.org/

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
  push:
    branches:
      - master

jobs:
  requireLabel:
    name: Require Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Uploads repository content to the runner
      - name: add-label
        id: add-label
        uses: actions/labeler@v5
        with:
          sync-labels: true
          configuration-path: .github/labeler.yml
      - name: Print New Labels
        id: extract_labels
        run: |
          echo "New Labels: ${{ steps.add-label.outputs.new-labels}}"
          echo "All Labels: ${{ steps.add-label.outputs.all-labels}}"
          echo "Removed Labels: ${{contains(steps.add-label.outputs.new-labels, 'docs-update')}}"
      - uses: zwaldowski/match-label-action@v2
        if: contains(steps.add-label.outputs.new-labels, 'docs-update') == false
        with:
          allowed: major release, minor release, patch release
